### PR TITLE
fix: fixed issue with pgsql connection

### PR DESCRIPTION
**Pull request by Boring-Mind**
I've experienced a bug with connection to postgresql. Fix is attached.

### CODE REVIEW

**Comment by igortg** [comment]
Seems strange. Are you sure you defined the `database_url` fixture in your `conftest.py`?
```
@pytest.fixture(scope="session")
def database_url():
    return "postgresql+asyncpg://postgres:masterkey@localhost/dbtest"

**Comment by Boring-Mind** [comment]
Yeah, definitely. Maybe it's because I'm working with the postgre 13?

**Comment by m-vellinga** [comment]
I also ran into this, the reason is actually this from the [postgres docs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS)

> The database name. Defaults to be the same as the user name. In certain contexts, the value is checked for extended formats; see Section 34.1.1 for more details on those.

"postgres" is the default database that always exists. So if you use a username that's not "postgres" it will by default pick that username from the URL and use it as dbname. Reason being setting the database to an empty string in create/drop database. Essentially this happening:

```
@pytest.fixture(scope="session")
def database_url():
    return "postgresql+asyncpg://myuser:mypassword@localhost/dbtest"

dbms_url = url.set(database="")
print(dbms_url)
# "postgresql+asyncpg://myuser:mypassword@localhost/"
# Which postgres itself wel interpret as:
# "postgresql+asyncpg://myuser:mypassword@localhost/myuser"
```

**Comment by igortg** [comment]
Thks to investigate that @m-vellinga 

I think it's possible to have a Postgres instance without a "postgres" database (see POSTGRES_DB Env Var description on [Postgres - Official Docker Image docs](https://hub.docker.com/_/postgres/)) - but since this seems pretty non-standard, let's go with the solution suggested by @Boring-Mind

**Comment by m-vellinga** [comment]
I don't think will be a problem based on [these docs](https://www.postgresql.org/docs/13/manage-ag-createdb.html)

> Since you need to be connected to the database server in order to execute the CREATE DATABASE command, the question remains how the first database at any given site can be created. The first database is always created by the initdb command when the data storage area is initialized. (See Section 18.2.) This database is called postgres. So to create the first “ordinary” database you can connect to postgres.

I tried using POSTGRES_DB with a different name and the postgres database still exists regardless.

**Comment by igortg** [comment]
Today I learn 😄 Thks again

**Pull request merged**
